### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by SehejBakshi** [nurjan84/dc-tts-keras#1]
`NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:/Users/Public/Anaconda/Projects/DeepInfoLab/TTS3/logdir/checkpoints/cp-0005.ckpt`

I am getting this error repeatedly. Could you please help?

**Comment by nurjan84** [comment]
it can not find saved checkpoint file. You can comment out #model.load weights. New checkpoints wil be saved during training

**Comment by SehejBakshi** [comment]
Thank You!
