### ISSUE TITLE
Cannot  run synthesize.py

### ISSUE THREAD

**Issue by SehejBakshi** [nurjan84/dc-tts-keras#2]
Hi again! 
I preprocessed and trained the model successfully with the given Hyperparameters (except I lowered batch_size to 16) but could not run the synthesize.py file. Since my system is not high end, to check whether the model was working, I set the epochs in `train_text_to_mel_model()` as 10 with 10 steps_per_epoch and the same in `train_SSRN_model()`. But it gave me an error of this sort: `librosa.util.exceptions.ParameterError: Target size (158) must be at least input size (1102)`. I then lowered the sample_rate to around 3000 and then got this error: `ValueError: operands could not be broadcast together with shapes (80,310) (1025,310)`. Even if I test for just `test_text2mel_model `, it gives me the same error.
Could you please tell me what I am doing wrong?

**Comment by nurjan84** [comment]
Hi!
As far as I know sampling_rate, n_fft, hop_length are depends on each other. You may search it on Google.
So, when you changing sampling rate , you have to recalculate other parameters. Then you have to resample all you dataset, preprocess and train model again.

Here is an example of audio parameters for 22050Hz , that worked for me:

 # signal processing
    sampling_rate = 22050  # Sampling rate.
    n_fft = 1024  # fft points (samples)
    frame_shift = 0.0125  # seconds
    frame_length = 0.05  # seconds
    # hop_length = int(sampling_rate * frame_shift)  # samples. =276.
    # win_length = int(sampling_rate * frame_length)  # samples. =1102.
    hop_length = 256
    win_length = None
    n_mels = 80  # Number of Mel banks to generate
    n_mags = 513  # Number of Mag banks to generate
    power = 1.5  # Exponent for amplifying the predicted magnitude
    n_iter = 50  # Number of inversion iterations
    preemphasis = .97
    max_db = 100
    ref_db = 20

**Comment by SehejBakshi** [comment]
Thank You. I'll try this out and let you know if this works
